name: S3 Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Invalidate CloudFront
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                  DISTRIBUTION: ${{ secrets.DISTRIBUTION_MASTER }}
                  PATHS: '/*'
                  AWS_REGION: 'us-east-1'
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: sa-east-1

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Use .npmrc
              uses: bduff9/use-npmrc@v1.1
              with:
                  dot-npmrc: ${{ secrets.DOT_NPMRC }}

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test:headless

            - name: Build
              run: npm run build:prod

            - name: Deploy
              if: success()
              run: aws s3 sync ./dist/zoppy-FE s3://${{ secrets.AWS_S3_BUCKET_MASTER }}
